version: "3"

volumes:
  pg_project:
services:
  app_db:
    build: docker_db/
    ports:
      - 5460:5460
  pg_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5666}:5432
  #database:
  #  image: postgres
  #  environment:
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_USER=user
  #    - POSTGRES_DB=data_base
  #    - DB_HOST=5432
  #  ports:
  #    - 5432:5432